name: cornerstone-gui

# Triggered after a branch is created, a tag or a branch is pushed or a PR with changes in 'cornerstone/**' is submitted
on:
  create:
  push:
  pull_request:
    paths:
      - "cornerstone/**"
jobs:
  unit-tests:
    name: (cornerstone-gui) Unit Tests #  Path to help identify each job in the status checks
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'ci skip') == false # If the commit message contains 'ci skip', it won't be necessary to run this job
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm check-licenses and test
        run: |
          cd cornerstone
          npm ci
          npm run lint
          npm run check-licenses
          npm test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: cornerstone/coverage/lcov.info # Created when 'npm test' is executed
          flags: cornerstone # Flags allow you to isolate coverage reports for different tests
          name: cornerstone-gui # Custom name for the upload

  docker-hub:
    needs: unit-tests
    name: (cornerstone-gui) Build and Publish image to DockerHub # Path to help identify each job in the status checks
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/pull/') == false # If this is a PR, it won't run
    steps:
      - name: Owner Repository
        id: get_owner
        run: |
          export OWNER=$(echo ${{ github.repository }} | cut -f1 -d"/")
          echo Current Owner is $OWNER
          echo ::set-output name=owner::$OWNER

      - name: Checkout
        uses: actions/checkout@v1

      - name: Build and Push
        uses: elgohr/Publish-Docker-Github-Action@2.16
        with:
          name: ${{ steps.get_owner.outputs.owner }}/cornerstone-gui
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: cornerstone-gui
          buildoptions: " --label 'commit_sha'='${{ github.sha }}' " # Label with the built image's commit
          tag_names: true # Whether tag will be based in the branch name or in the tag name
